local builtin = require("telescope.builtin")
local harpoon_mark = require("harpoon.mark")
local harpoon_ui = require("harpoon.ui")

vim.keymap.set("n", "<leader>ff", builtin.find_files, { desc = "Telescope find files" })
vim.keymap.set("n", "<leader>fw", builtin.live_grep, { desc = "Telescope live grep" })
vim.keymap.set("n", "<leader>fb", builtin.buffers, { desc = "Telescope buffers" })
vim.keymap.set("n", "<leader>fh", builtin.help_tags, { desc = "Telescope help tags" })

-- custom theme picker
vim.keymap.set("n", "<leader>th", function()
	builtin.colorscheme()
end, { desc = "Choose colorscheme" })
vim.keymap.set("n", "<leader>ts", function()
	require("statusbarcolors").colors()
end)

vim.keymap.set("n", "<leader>ha", harpoon_mark.add_file, { desc = "Harpoon Add file" })
vim.keymap.set("n", "<leader>hh", harpoon_ui.toggle_quick_menu, { desc = "Toggle Harpoon quick menu" })
vim.keymap.set("n", "<leader>hu", function()
	harpoon_ui.nav_file(1)
end, { desc = "Harpoon Navigate file 1" })
vim.keymap.set("n", "<leader>hi", function()
	harpoon_ui.nav_file(2)
end, { desc = "Harpoon Navigate file 2" })
vim.keymap.set("n", "<leader>ho", function()
	harpoon_ui.nav_file(3)
end, { desc = "Harpoon Navigate file 3" })
vim.keymap.set("n", "<leader>hp", function()
	harpoon_ui.nav_file(4)
end, { desc = "Harpoon Navigate file 4" })

vim.keymap.set("n", "<leader>u", vim.cmd.UndotreeToggle, { desc = "Open up undotree" })

vim.keymap.set("n", ";", ":")
vim.keymap.set({ "i", "n" }, "<C-s>", "<esc>:w<CR>", { desc = "Save file" })
-- vim.keymap.set('n', '<C-s>', ':w<CR>', { desc = 'Save file' })
vim.keymap.set("n", "<leader>wq", "<C-w>o", { desc = "Close all other windows" })

vim.keymap.set("n", "<C-d>", "<C-d>zz", { desc = "Go down half a page" })
vim.keymap.set("n", "<C-u>", "<C-u>zz", { desc = "Go up half a page" })
vim.keymap.set("n", "+", "<C-w>+")
vim.keymap.set("n", "-", "<C-w>-")
vim.keymap.set("n", ">", "<C-w>>")
vim.keymap.set("n", "<", "<C-w><")
vim.keymap.set("n", "<leader>>", ">>")
vim.keymap.set("n", "<leader><", "<<")
vim.keymap.set("n", "<Up>", "<C-w>k")
vim.keymap.set("n", "<Down>", "<C-w>j")
vim.keymap.set("n", "<Right>", "<C-w>l")
vim.keymap.set("n", "<Left>", "<C-w>h")
vim.keymap.set("i", "<Up>", "<esc><C-w>ki")
vim.keymap.set("i", "<Down>", "<esc><C-w>ji")
vim.keymap.set("i", "<Right>", "<esc><C-w>li")
vim.keymap.set("i", "<Left>", "<esc><C-w>hi")

vim.keymap.set("n", "<C-,>", "<Cmd>BufferPrevious<CR>", { desc = "Previous Buffer", noremap = true, silent = true })
vim.keymap.set("n", "<C-.>", "<Cmd>BufferNext<CR>", { desc = "Next Buffer", noremap = true, silent = true })
vim.keymap.set("n", "<leader>q", "<Cmd>BufferClose<CR>", { desc = "Close Buffer", noremap = true, silent = true })

vim.keymap.set("n", "gd", function()
	vim.lsp.buf.definition()
end, { desc = "Go to definition" })
vim.keymap.set("n", "<C-h>", function()
	vim.lsp.buf.signature_help()
end, { desc = "Get signature help" })
vim.keymap.set("n", "<leader>ra", function()
	vim.lsp.buf.rename()
end, { desc = "Rename symbol" })

vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv", { desc = "Move block in visual selection down" })
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv", { desc = "Move block in visual selection up" })

vim.keymap.set("n", "J", "mzJ`z", { desc = "Move next line to the current line" })

vim.keymap.set("x", "<leader>p", '"_dP', { desc = "Paste and replace text without overwriting paste buffer" })
